### ISSUE TITLE
命令无法运行

### ISSUE THREAD

**Issue by bgdsh** [node-weixin/node-weixin-express#9]
```
Marcs-iMac:WeixinExpress bgd$ weixin weixin_config.yaml

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
  at module.exports (/usr/local/lib/node_modules/node-weixin-express/lib/parser.js:42:3)
  at Object.<anonymous> (/usr/local/lib/node_modules/node-weixin-express/lib/cli.js:43:12)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.runMain (module.js:575:10)
  at run (bootstrap_node.js:352:7)
  at startup (bootstrap_node.js:144:9)
  at bootstrap_node.js:467:3
```

加上`--config`也是一样的。

**Comment by calidion** [comment]
你的config 文件内容是什么？

**Comment by calidion** [comment]
只发已经添写的字段即可

**Comment by calidion** [comment]
刚看了一下是文档没有更新。
将
server包括下面的所有配置移到
weixin:
下面应该就可以了。

**Comment by bgdsh** [comment]
OK 我试试，感谢回复。
